import os
from dotenv import load_dotenv

load_dotenv()

OLLAMA_MODEL=os.getenv("OLLAMA_MODEL")
OLLAMA_EMBEDDING_MODEL=os.getenv("OLLAMA_EMBEDDING_MODEL")
OLLAMA_BASE_URL=os.getenv("OLLAMA_BASE_URL")

LANGSMITH_TRACING=os.getenv("LANGSMITH_TRACING")
LANGSMITH_ENDPOINT=os.getenv("LANGSMITH_ENDPOINT")
LANGSMITH_API_KEY=os.getenv("LANGSMITH_API_KEY")
LANGSMITH_PROJECT=os.getenv("LANGSMITH_PROJECT")